/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      'Pets',
      [
        {
          name: 'Бобик',
          type: 'Собака',
          sex: '♂',
          age: 3,
          city: 'Москва',
          pedigree: 'Бордер Колли',
          info: 'Любит играть с палочкой',
          image: '1.jpg',
          user_id: 2,
        },
        {
          name: 'Шарик',
          type: 'Собака',
          sex: '♂',
          age: 1,
          city: 'Санкт-Петербург',
          pedigree: 'Овчарка',
          info: 'Любит изучать композицию, а также изучать их разные исполнители',
          image: '6.jpg',
          user_id: 2,
        },
        {
          name: 'Рекс',
          type: 'Собака',
          sex: '♂',
          age: 2,
          city: 'Уфа',
          pedigree: 'Лабрадор',
          info: 'Любит изучать композицию, а также изучать их разные исполнители',
          image: '2.jpg',
          user_id: 3,
        },
        {
          name: 'Лайка',
          type: 'Собака',
          sex: '♀',
          age: 4,
          city: 'Улан-Удэ',
          pedigree: 'Корги',
          info: 'Любит изучать композицию, а также изучать их разные исполнители',
          image: '3.jpg',
          user_id: 2,
        },
        {
          name: 'Барон',
          type: 'Кошка',
          sex: '♂',
          age: 6,
          city: 'Москва',
          pedigree: 'Сибирская',
          info: 'Любит изучать композицию, а также изучать их разные исполнители',
          image: 'photo_2023-07-07_10-29-47.jpg',
          user_id: 1,
        },
        {
          name: 'Багира',
          type: 'Кошка',
          sex: '♀',
          age: 6,
          city: 'Санкт-Петербург',
          pedigree: 'Пушистая',
          info: 'Любит изучать композицию, а также изучать их разные исполнители',
          image: '10.jpg',
          user_id: 3,
        },
        {
          name: 'Мурка',
          type: 'Кошка',
          sex: '♀',
          age: 1,
          city: 'Владимир',
          pedigree: 'Британская',
          info: 'Любит изучать композицию, а также изучать их разные исполнители',
          image: '11.jpg',
          user_id: 2,
        },
        {
          name: 'Чебурашка',
          type: 'Кошка',
          sex: '♂',
          age: 3,
          city: 'Екатеринбург',
          pedigree: 'Дикая',
          info: 'Любит изучать композицию, а также изучать их разные исполнители',
          image: '12.jpg',
          user_id: 1,
        },
        {
          name: 'Кузя',
          type: 'Кошка',
          sex: '♂',
          age: 2,
          city: 'Москва',
          pedigree: 'Дворовая',
          info: 'Любит изучать композицию, а также изучать их разные исполнители',
          image: '13.jpg',
          user_id: 1,
        },
        {
          name: 'Мурка',
          type: 'Кошка',
          sex: '♂',
          age: 2,
          city: 'Москва',
          pedigree: 'Русская голубая',
          info: 'Любит изучать композицию, а также изучать их разные исполнители',
          image: '14.jpg',
          user_id: 4,
        },
        {
          name: 'Маркиз',
          type: 'Кошка',
          sex: '♂',
          age: 4,
          city: 'Москва',
          pedigree: 'Русская голубая',
          info: 'Любит изучать композицию, а также изучать их разные исполнители',
          image: '15.jpg',
          user_id: 5,
        },

        {
          name: 'Вася',
          type: 'Кошка',
          sex: '♂',
          age: 3,
          city: 'Москва',
          pedigree: 'Манул',
          info: 'Любит изучать композицию, а также изучать их разные исполнители',
          image: '16.jpg',
          user_id: 6,
        },

        {
          name: 'Мурзик',
          type: 'Кошка',
          sex: '♂',
          age: 2,
          city: 'Москва',
          pedigree: 'Манул',
          info: 'Любит изучать композицию, а также изучать их разные исполнители',
          image: '17.jpg',
          user_id: 6,
        },

        {
          name: 'Федя',
          type: 'Кошка',
          sex: '♂',
          age: 3,
          city: 'Москва',
          pedigree: 'Манул',
          info: 'Любит изучать композицию, а также изучать их разные исполнители',
          image: '18.jpg',
          user_id: 6,
        },

        {
          name: 'Шварц',
          type: 'Кошка',
          sex: '♂',
          age: 3,
          city: 'Москва',
          pedigree: 'Манул',
          info: 'Любит изучать композицию, а также изучать их разные исполнители',
          image: '19.jpg',
          user_id: 6,
        },

        {
          name: 'Миша',
          type: 'Кошка',
          sex: '♂',
          age: 3,
          city: 'Москва',
          pedigree: 'Манул',
          info: 'Любит изучать композицию, а также изучать их разные исполнители',
          image: '20.jpg',
          user_id: 6,
        },

        {
          name: 'Иннокентий',
          type: 'Кошка',
          sex: '♂',
          age: 3,
          city: 'Москва',
          pedigree: 'Манул',
          info: 'Любит изучать композицию, а также изучать их разные исполнители',
          image: '21.jpg',
          user_id: 6,
        },

        {
          name: 'Саня',
          type: 'Кошка',
          sex: '♂',
          age: 3,
          city: 'Москва',
          pedigree: 'Манул',
          info: 'Любит изучать композицию, а также изучать их разные исполнители',
          image: '22.jpg',
          user_id: 6,
        },

        {
          name: 'Вельзевул',
          type: 'Кошка',
          sex: '♂',
          age: 3,
          city: 'Москва',
          pedigree: 'Манул',
          info: 'Любит изучать композицию, а также изучать их разные исполнители',
          image: '23.jpg',
          user_id: 6,
        },

        {
          name: 'Кентавр',
          type: 'Кошка',
          sex: '♂',
          age: 3,
          city: 'Москва',
          pedigree: 'Манул',
          info: 'Любит изучать композицию, а также изучать их разные исполнители',
          image: '23.jpg',
          user_id: 6,
        },
      ],
      {},
    );
  },

  async down(queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
    await queryInterface.bulkDelete('Pets', null, {});
  },
};
