/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      'Pets',
      [
        {
          name: 'Бобик',
          type: 'Собака',
          sex: '♂',
          age: 3,
          city: 'Москва',
          pedigree: 'Бордер Колли',
          info: 'Любит играть с палочкой',
          image: 'vzglad-sobaka1234.jpg',
          user_id: 2,
        },
        {
          name: 'Шарик',
          type: 'Собака',
          sex: '♂',
          age: 1,
          city: 'Санкт-Петербург',
          pedigree: 'Овчарка',
          info: 'Любит изучать композицию, а также изучать их разные исполнители',
          image: 'screen-6.jpg',
          user_id: 2,
        },
        {
          name: 'Рекс',
          type: 'Собака',
          sex: '♂',
          age: 2,
          city: 'Уфа',
          pedigree: 'Лабрадор',
          info: 'Любит изучать композицию, а также изучать их разные исполнители',
          image: '1568648029_ryzhiy-labrador.jpg',
          user_id: 3,
        },
        {
          name: 'Лайка',
          type: 'Собака',
          sex: '♀',
          age: 4,
          city: 'Улан-Удэ',
          pedigree: 'Корги',
          info: 'Любит изучать композицию, а также изучать их разные исполнители',
          image: '8731ebe64395319075e5423d0462b540.jpg',
          user_id: 2,
        },
        {
          name: 'Барон',
          type: 'Кошка',
          sex: '♂',
          age: 6,
          city: 'Москва',
          pedigree: 'Сибирская',
          info: 'Любит изучать композицию, а также изучать их разные исполнители',
          image: 'photo_2023-07-07_10-29-47.jpg',
          user_id: 1,
        },
        {
          name: 'Багира',
          type: 'Кошка',
          sex: '♀',
          age: 6,
          city: 'Санкт-Петербург',
          pedigree: 'Пушистая',
          info: 'Любит изучать композицию, а также изучать их разные исполнители',
          image: 'photo_2023-07-07_10-31-19.jpg',
          user_id: 3,
        },
        {
          name: 'Мурка',
          type: 'Кошка',
          sex: '♀',
          age: 1,
          city: 'Владимир',
          pedigree: 'Британская',
          info: 'Любит изучать композицию, а также изучать их разные исполнители',
          image: 'photo_2023-07-07_10-39-43.jpg',
          user_id: 2,
        },
        {
          name: 'Чебурашка',
          type: 'Кошка',
          sex: '♂',
          age: 3,
          city: 'Екатеринбург',
          pedigree: 'Дикая',
          info: 'Любит изучать композицию, а также изучать их разные исполнители',
          image: 'photo_2023-07-07_12-13-57.jpg',
          user_id: 1,
        },
        {
          name: 'Кузя',
          type: 'Кошка',
          sex: '♂',
          age: 2,
          city: 'Москва',
          pedigree: 'Дворовая',
          info: 'Любит изучать композицию, а также изучать их разные исполнители',
          image: 'photo_2023-07-07_12-14-32.jpg',
          user_id: 1,
        },
        {
          name: 'Мурка',
          type: 'Кошка',
          sex: '♂',
          age: 2,
          city: 'Москва',
          pedigree: 'Русская голубая',
          info: 'Любит изучать композицию, а также изучать их разные исполнители',
          image: 'photo_2023-07-07_14-19-25.jpg',
          user_id: 4,
        },
        {
          name: 'Маркиз',
          type: 'Кошка',
          sex: '♂',
          age: 4,
          city: 'Москва',
          pedigree: 'Русская голубая',
          info: 'Любит изучать композицию, а также изучать их разные исполнители',
          image: 'photo_2023-07-07_12-15-11.jpg',
          user_id: 5,
        },

        {
          name: 'Вася',
          type: 'Кошка',
          sex: '♂',
          age: 3,
          city: 'Москва',
          pedigree: 'Манул',
          info: 'Любит изучать композицию, а также изучать их разные исполнители',
          image: 'photo_2023-07-07_13-20-07.jpg',
          user_id: 6,
        },

        {
          name: 'Мурзик',
          type: 'Кошка',
          sex: '♂',
          age: 2,
          city: 'Москва',
          pedigree: 'Манул',
          info: 'Любит изучать композицию, а также изучать их разные исполнители',
          image: '2e1b8f0bc72ea2d042a110aa4b9a1c12_0x0w.jpg',
          user_id: 6,
        },

        {
          name: 'Федя',
          type: 'Кошка',
          sex: '♂',
          age: 3,
          city: 'Москва',
          pedigree: 'Манул',
          info: 'Любит изучать композицию, а также изучать их разные исполнители',
          image: '1669404561_damion-club-p-kotik-s-golubimi-glazami-oboi-1.jpg',
          user_id: 6,
        },

        {
          name: 'Шварц',
          type: 'Кошка',
          sex: '♂',
          age: 3,
          city: 'Москва',
          pedigree: 'Манул',
          info: 'Любит изучать композицию, а также изучать их разные исполнители',
          image: 'img_7677.jpg',
          user_id: 6,
        },

        {
          name: 'Миша',
          type: 'Кошка',
          sex: '♂',
          age: 3,
          city: 'Москва',
          pedigree: 'Манул',
          info: 'Любит изучать композицию, а также изучать их разные исполнители',
          image: 'photo_2023-07-07_10-48-45.jpg',
          user_id: 6,
        },

        {
          name: 'Иннокентий',
          type: 'Кошка',
          sex: '♂',
          age: 3,
          city: 'Москва',
          pedigree: 'Манул',
          info: 'Любит изучать композицию, а также изучать их разные исполнители',
          image: 'Russkaya-golubaya-e1623600193791.jpg',
          user_id: 6,
        },

        {
          name: 'Саня',
          type: 'Кошка',
          sex: '♂',
          age: 3,
          city: 'Москва',
          pedigree: 'Манул',
          info: 'Любит изучать композицию, а также изучать их разные исполнители',
          image: '1663288675_6-mykaleidoscope-ru-p-emotsii-kotov-emotsii-6.jpg',
          user_id: 6,
        },

        {
          name: 'Вельзевул',
          type: 'Кошка',
          sex: '♂',
          age: 3,
          city: 'Москва',
          pedigree: 'Манул',
          info: 'Любит изучать композицию, а также изучать их разные исполнители',
          image: '3130x2348_605244_[www.ArtFile.ru].jpg',
          user_id: 6,
        },

        {
          name: 'Кентавр',
          type: 'Кошка',
          sex: '♂',
          age: 3,
          city: 'Москва',
          pedigree: 'Манул',
          info: 'Любит изучать композицию, а также изучать их разные исполнители',
          image: 'maxresdefault-9.jpg',
          user_id: 6,
        },
      ],
      {},
    );
  },

  async down(queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
    await queryInterface.bulkDelete('Pets', null, {});
  },
};
